# Generated by Django 3.0.4 on 2020-03-06 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=200)),
                ('data_nascimento', models.DateTimeField()),
                ('tutor', models.TextField(max_length=200)),
                ('data_castracao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelagem',
            fields=[
                ('id_pelagem', models.AutoField(primary_key=True, serialize=False)),
                ('dsc_pelagem', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProcedimento',
            fields=[
                ('id_tpprocedimento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_procedimento', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id_veterinario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=200)),
                ('matricula', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id_procedimento', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('valor_procedimento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_tpprocedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamento.TipoProcedimento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamento.Paciente')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamento.Veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamento.Procedimento')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_pelagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamento.Pelagem'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='veterinario_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamento.Veterinario'),
        ),
    ]
